[Alex] Step 1- 회원 가입 및 목록 조회 기능
codesquad-members-2024/be-spring-cafe pull request #8
Opened 2024-04-09 07:44 UTC by horanga

## 구현 내용
1)회원가입 기능
2)비밀번호 암호화하고 저장하는 기능
3)회원 목록 조회
4)회원 프로필 기능

## 고민 사항

1)이번에 처음으로 spring 시큐리티를 사용해봤는데, 암호화를 비롯해 여러 기능을 쓸 수 있다는 점은 좋은 거 같습니다. 다만, spring 시큐리티를 쓰면 어떤 페이지들이 보안문제로 forbbiden이 되버려서 그걸 springconfig에서 풀어줘야 하는데...원래 이렇게 하는 거 같긴한데 이렇게 해도 괜찮을지 고민이 되네요

2)createForm에서 회원정보를 받아서 db에 넣는데, 이 회원정보를 다시 dto처럼 사용해서 model에 던져줘도 괜찮을지?고민했는데 gpt에게 물어보니 보안 문제상 비밀번호가 있는 form을 dto로 쓰는 게 좋은 선택은 아닌 거 같아서 dto를 별도로 만들었습니다.

## 기타

2024-04-11 03:48 UTC, honux77 requested changes
@horanga 스프링 시큐리티 이번 단계랑 다음 단계에서는 쓰면 안 됩니다. 
의존성 제거하고 걷어 주세요.

2024-04-11 06:13 UTC, horanga commented
스프링 시큐리티 의존성 제거했습니다.

2024-04-12 00:20 UTC, honux77 commented on src/main/java/springcafe/dto/UserCreateForm.java
여기서 사용하는 DTO들의 필요성이 잘 느껴지지 않네요.

2024-04-12 00:22 UTC, honux77 commented on src/main/java/springcafe/repository/UserRepositoryImpl.java
> +    public User findById(String id) {
findAll 과 findById 모두를 효과적으로 구현하기 위해서는 List가 아닌 다른 자료구조를 쓰는게 좋았을 것 같습니다.

2024-04-12 00:23 UTC, honux77 commented on src/main/java/springcafe/user/service/UserService.java
> +public class UserService {
수업 때도 말했지만 이 서비스도 사실은 거의 필요가 없어 보입니다.

2024-04-12 00:24 UTC, honux77 commented on src/main/java/springcafe/controller/UserController.java
> +        List<UserDto> userDto = userService.findAll();
```suggestion
        List<UserDto> users= userService.findAll();
```

2024-04-12 00:25 UTC, honux77 approved these changes
고치느라 고생하셨어요! 화이팅!

2024-04-12 00:25 UTC, merged